### ISSUE TITLE
ask lucas to comment on run_disperser_parallel npart argument

### ISSUE THREAD

**Issue by garbulinskamaja** [lhenneman/disperseR#15]
@lhenneman

**Comment by garbulinskamaja** [comment]
same for start.hours in `define_inputs()`

**Comment by lhenneman** [comment]
I think it's best to have npart default to 100 to stay consistent with our original analyses.

And I agree it's best to keep start.hours defaulting to c(0, 6, 12, 18).

**Comment by garbulinskamaja** [comment]
I think we need more explanation for the rational in the vignette or help files.

**Comment by lhenneman** [comment]
commented.
