### ISSUE TITLE
counties data 

### ISSUE THREAD

**Issue by garbulinskamaja** [lhenneman/disperseR#17]
@lhenneman made new functions for hyspdisp that should be integrated in disperseR. Think about solutions to make less functions. 

https://github.com/lhenneman/hyspdisp/blob/dev2/R/hyspdisp_county_link.R
Here's linking to a grid: https://github.com/lhenneman/hyspdisp/blob/dev2/R/hyspdisp_grid_link.R

Here's combining counties: https://github.com/lhenneman/hyspdisp/blob/dev2/R/combine_monthly_countylinks.R
Here's combining grid: https://github.com/lhenneman/hyspdisp/blob/dev2/R/combine_monthly_gridlinks.R

Here's calculating county exposure: https://github.com/lhenneman/hyspdisp/blob/dev2/R/calc_county_exposure.R
Here's calculating grid exposure: https://github.com/lhenneman/hyspdisp/blob/dev2/R/calc_grid_exposure.R

**Comment by lhenneman** [comment]
solved, introduced the link.to option in functions that can be applied to counties and grids
