### ISSUE TITLE
avoid loading libraries in vignettes

### ISSUE THREAD

**Issue by lhenneman** [lhenneman/disperseR#22]
For an installation with build_vignettes = TRUE, all the necessary libraries are loaded, resulting in many masked functions. @garbulinskamaja is it better to avoid loading libraries and reference functions' libraries specifically, for example ggplot2::ggplot?

**Comment by garbulinskamaja** [comment]
makes sense. I will try to take them out and test!

**Comment by garbulinskamaja** [comment]
I can't knit the markdown file if I don't include them at the beginning.

**Comment by lhenneman** [comment]
Gotcha. No worries about it then.
